version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - consumer_net
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=consumer

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - consumer_net

  adminer:
    image: adminer
    ports:
      - "8083:8080"
    expose:
      - "8083"
    networks:
      - consumer_net

networks:
  consumer_net:
    driver: bridge